[versions]
agp = "8.13.2"
kotest = "6.0.7"
kotlin = "2.3.0"
ksp = "2.3.4"
android-minSdk = "24"
android-compileSdk = "36"

[libraries]
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-junit-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
